[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/oschwald/geoip2-golang"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/xtaci/smux"
  version = "1.2.6"

[[constraint]]
  name = "github.com/pierrec/lz4"
  version = "2.2.3"
